name: Build Android Debug APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'


    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Generate Gradle wrapper if missing
      run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "gradle-wrapper.jar missing, regenerating..."
            curl -L https://services.gradle.org/distributions/gradle-8.4-bin.zip -o gradle-8.4-bin.zip
            unzip gradle-8.4-bin.zip -d gradle-temp
            mv gradle-temp/gradle-8.4 gradle
            rm -rf gradle-temp gradle-8.4-bin.zip
          fi

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
